services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ../frontend
    volumes:
      - frontend_build:/result_build

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
    - frontend_build:/usr/share/nginx/html
    - static_volume:/usr/share/nginx/html/backend_static
    - media_volume:/usr/share/nginx/html/media
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  frontend_build:
  static_volume:
  media_volume: